import {useEventListener, useRafFn} from '@vueuse/core'
import {scalar} from 'linearly'
import {debounce} from 'lodash'
import {MaybeRef, readonly, ref} from 'vue'

import {DragEvent, useElementDrag} from './useElementDrag'

// 慣性スクロールを無効化するまでの指を動かさないでいる時間 (sec)
const InertiaCancelDuration = 0.2

// 慣性スクロールが効き始める最低速度 (vh/sec)
const MinInertiaScrollSpeedInVh = 10

// ホイール入力が途切れてから「指が離れた」とみなすまでの時間 (ms)
const WheelIdleMs = 100

// ホイールの指速度を推定する EMA の半減期 (sec)。トラックパッドのイベントは
// 8〜16ms 間隔で来るので、直近 2〜3 イベントぶんを平均する程度
const WheelVelocityHalfLifeSec = 0.03

// この時間以上ホイールが途切れたら速度推定をリセットする (sec)
const WheelVelocityResetSec = 0.1

export interface VirtualScrollEvent {
	offset: number
	delta: number
}

interface UseVirtualScrollOptions {
	onSwipe: (e: VirtualScrollEvent) => void
	onPointerdown: (e: VirtualScrollEvent) => void
	onPointerup: (e: VirtualScrollEvent) => void
	mapScroll: (y: number) => number
}

export function useVirtualScroll(
	el: MaybeRef<HTMLElement | null>,
	options: UseVirtualScrollOptions
) {
	const scroll = ref(0)

	let swipeDelta = 0

	/** Pepresented in px / second */
	let inertiaSpeed = 0

	let easeSpeedOptions: null | {
		get: () => number
		onReach: () => void
		// Fired when the ease is canceled by `cancelInertia()` before it
		// reaches `get()`. Without this, callers that track an implicit
		// "we are resuming" state via the ease have no way to learn the
		// ease was killed and can leak that state forever.
		onAbort?: () => void
	} = null

	useEventListener(el, 'wheel', onWheel)

	// Scroll by wheel
	//
	// A wheel "gesture" has no begin/end events, so we synthesize them:
	// the first wheel event fires onPointerdown, and onPointerup fires
	// once no wheel event has arrived for `WheelIdleMs`.
	//
	// On Chromium 151+ `WheelEvent.momentum` tells us whether an event was
	// generated by the platform's inertial scrolling (fingers already off
	// the trackpad) rather than by the fingers themselves. When we see the
	// first momentum event we treat it as the pointerup: we stop consuming
	// the platform's momentum tail and hand the measured finger velocity
	// to our own inertia so the caller's resume ease can start right away,
	// instead of waiting for the tail to die out plus the idle timeout.
	// Browsers without `momentum` keep the idle-timeout behavior.
	let wheelGestureActive = false
	let wheelMomentumActive = false

	/** Finger velocity measured from non-momentum wheel events (px / sec) */
	let wheelVelocity = 0
	let lastWheelTime = 0

	function onWheel(e: WheelEvent) {
		const isMomentum = (e as WheelEvent & {momentum?: boolean}).momentum

		if (isMomentum === true) {
			if (wheelGestureActive && !wheelMomentumActive) {
				wheelMomentumActive = true
				willTriggerOnPointerup.cancel()
				endWheelGesture(-wheelVelocity)
			}
			// Our RAF loop drives the scroll from here on.
			return
		}

		wheelMomentumActive = false
		swipeDelta = inertiaSpeed = 0

		const now = performance.now()
		const dt = (now - lastWheelTime) / 1000
		lastWheelTime = now

		if (dt > WheelVelocityResetSec || dt <= 0) {
			wheelVelocity = 0
		} else {
			const ratio = 1 - 2 ** (-dt / WheelVelocityHalfLifeSec)
			wheelVelocity = scalar.lerp(wheelVelocity, e.deltaY / dt, ratio)
		}

		scroll.value = options.mapScroll(scroll.value + e.deltaY)

		if (!wheelGestureActive) {
			// The caller may call cancelInertia() from here, which resets the
			// wheel gesture state, so mark the gesture active *after* it.
			options.onPointerdown({
				offset: 0,
				delta: 0,
			})
			wheelGestureActive = true
		}

		options.onSwipe({
			offset: 0,
			delta: e.deltaY,
		})

		willTriggerOnPointerup()
	}

	function endWheelGesture(releaseSpeed: number) {
		wheelGestureActive = false
		wheelVelocity = 0
		swipeDelta = 0
		inertiaSpeed = clampInertiaSpeed(releaseSpeed)

		options.onPointerup({
			offset: 0,
			delta: 0,
		})
	}

	const willTriggerOnPointerup = debounce(() => {
		endWheelGesture(0)
	}, WheelIdleMs)

	/** Below the minimum speed, a release does not start inertia. */
	function clampInertiaSpeed(speed: number) {
		const minInertiaSpeed =
			(window.innerHeight * MinInertiaScrollSpeedInVh) / 100

		return Math.abs(speed) < minInertiaSpeed ? 0 : speed
	}

	// Scroll by swipe

	const {dragging} = useElementDrag(el, {
		onPointerdown,
		onDrag,
		onPointerup,
	})

	function onPointerdown() {
		// Notify the caller *before* canceling inertia. The caller may want
		// to peek at the in-flight resume ease (via its own bookkeeping) to
		// decide what state to transition to. If we cancel first, the
		// onAbort hook fires and erases that context, so the caller sees a
		// clean slate and can't tell that a resume was in progress.
		options.onPointerdown({
			offset: 0,
			delta: 0,
		})

		cancelInertia()
	}

	function onDrag(e: DragEvent) {
		scroll.value = options.mapScroll(scroll.value - e.movement[1])

		swipeDelta += e.movement[1]

		onLongPress()

		options.onSwipe({
			offset: e.offset[1],
			delta: -e.movement[1],
		})
	}

	const onLongPress = debounce(
		() => {
			if (!dragging.value) return
			cancelInertia()
		},
		InertiaCancelDuration * 1000,
		{}
	)

	function onPointerup(e: DragEvent) {
		inertiaSpeed = clampInertiaSpeed(inertiaSpeed)
		swipeDelta = 0

		options.onPointerup({
			offset: e.offset[1],
			delta: 0,
		})
	}

	// Inertial scrolling
	useRafFn(({delta: deltaTimeMs}) => {
		const deltaTime = deltaTimeMs / 1000
		const swipeSpeed = swipeDelta / deltaTime
		swipeDelta = 0

		// Lerp inertiaSpeed to swipeSpeed
		if (deltaTime > 0) {
			const directionChanged = swipeSpeed * inertiaSpeed < 0
			const swipeSpeedExceeded = Math.abs(swipeSpeed) > Math.abs(inertiaSpeed)

			if (directionChanged || swipeSpeedExceeded) {
				inertiaSpeed = swipeSpeed
			} else {
				const halfLife = dragging.value ? 0.05 : 1
				const ratio = 1 - 2 ** (-deltaTime / halfLife)

				inertiaSpeed = scalar.lerp(inertiaSpeed, swipeSpeed, ratio)
			}

			// Accelate/decelerate to the target speed
			if (easeSpeedOptions !== null) {
				const targetSpeed = easeSpeedOptions.get()
				const doAccelate = targetSpeed > inertiaSpeed

				const diff =
					Math.abs(inertiaSpeed - targetSpeed) / Math.abs(targetSpeed)

				const rate = scalar.efit(diff, 0, 10, 1000, 5000)

				inertiaSpeed += (doAccelate ? 1 : -1) * rate * deltaTime

				const reached = doAccelate
					? inertiaSpeed >= targetSpeed
					: inertiaSpeed <= targetSpeed

				if (reached) {
					inertiaSpeed = 0
					easeSpeedOptions.onReach()
					easeSpeedOptions = null
				}
			}
		}

		if (!dragging.value && Math.abs(inertiaSpeed) > 1) {
			const delta = inertiaSpeed * deltaTime
			scroll.value = options.mapScroll(scroll.value - delta)
		}
	})

	function cancelInertia() {
		swipeDelta = inertiaSpeed = 0
		wheelGestureActive = false
		wheelMomentumActive = false
		wheelVelocity = 0
		if (easeSpeedOptions !== null) {
			const aborted = easeSpeedOptions
			easeSpeedOptions = null
			aborted.onAbort?.()
		}
	}

	function scrollTo(y: number) {
		scroll.value = options.mapScroll(y)
	}

	function easeToSpeed(options: typeof easeSpeedOptions) {
		easeSpeedOptions = options
	}

	return {
		scroll: readonly(scroll),
		scrollTo,
		cancelInertia,
		easeToSpeed,
		dragging,
	}
}
